// Package cypher generates Neo4j Cypher statements from graph data.
package cypher

import (
	"fmt"
	"strings"

	"github.com/plexusone/graphfs/pkg/graph"
)

// Generator creates Neo4j Cypher CREATE statements from graph nodes and edges.
type Generator struct {
	// IncludeHeader adds usage comments at the top of the output.
	IncludeHeader bool

	// IncludeConstraint adds a UNIQUE constraint statement.
	IncludeConstraint bool
}

// NewGenerator creates a Generator with default settings.
func NewGenerator() *Generator {
	return &Generator{
		IncludeHeader:     true,
		IncludeConstraint: true,
	}
}

// Generate creates Cypher statements for all nodes and edges.
func (g *Generator) Generate(nodes []*graph.Node, edges []*graph.Edge) string {
	var sb strings.Builder

	if g.IncludeHeader {
		sb.WriteString("// Neo4j Cypher import script\n")
		sb.WriteString("// Generated by graphize\n")
		sb.WriteString("//\n")
		sb.WriteString("// Usage:\n")
		sb.WriteString("//   cat graph.cypher | cypher-shell -u neo4j -p password\n")
		sb.WriteString("//   Or paste into Neo4j Browser\n")
		sb.WriteString("\n")
	}

	if g.IncludeConstraint {
		sb.WriteString("// Create constraint for unique node IDs\n")
		sb.WriteString("CREATE CONSTRAINT node_id IF NOT EXISTS FOR (n:Node) REQUIRE n.id IS UNIQUE;\n\n")
	}

	// Create nodes
	sb.WriteString("// Create nodes\n")
	for _, n := range nodes {
		sb.WriteString(NodeToCreate(n))
		sb.WriteString("\n")
	}
	sb.WriteString("\n")

	// Create edges
	sb.WriteString("// Create relationships\n")
	for _, e := range edges {
		sb.WriteString(EdgeToCreate(e))
		sb.WriteString("\n")
	}

	return sb.String()
}

// NodeToCreate generates a CREATE statement for a single node.
func NodeToCreate(n *graph.Node) string {
	id := EscapeString(n.ID)
	label := EscapeString(n.Label)
	nodeType := EscapeString(n.Type)

	props := []string{
		fmt.Sprintf("id: '%s'", id),
		fmt.Sprintf("type: '%s'", nodeType),
	}

	if label != "" && label != id {
		props = append(props, fmt.Sprintf("label: '%s'", label))
	}

	for k, v := range n.Attrs {
		if v != "" {
			props = append(props, fmt.Sprintf("%s: '%s'", EscapeKey(k), EscapeString(v)))
		}
	}

	neoLabel := ToNeoLabel(n.Type)
	return fmt.Sprintf("CREATE (:%s {%s});", neoLabel, strings.Join(props, ", "))
}

// EdgeToCreate generates a CREATE statement for a single edge.
func EdgeToCreate(e *graph.Edge) string {
	from := EscapeString(e.From)
	to := EscapeString(e.To)
	relType := ToNeoRelType(e.Type)

	var props []string

	if e.Confidence != "" {
		props = append(props, fmt.Sprintf("confidence: '%s'", EscapeString(string(e.Confidence))))
	}

	if e.ConfidenceScore > 0 {
		props = append(props, fmt.Sprintf("confidence_score: %f", e.ConfidenceScore))
	}

	for k, v := range e.Attrs {
		if v != "" {
			props = append(props, fmt.Sprintf("%s: '%s'", EscapeKey(k), EscapeString(v)))
		}
	}

	var propsStr string
	if len(props) > 0 {
		propsStr = fmt.Sprintf(" {%s}", strings.Join(props, ", "))
	}

	return fmt.Sprintf("MATCH (a:Node {id: '%s'}), (b:Node {id: '%s'}) CREATE (a)-[:%s%s]->(b);",
		from, to, relType, propsStr)
}

// EscapeString escapes a string for use in Cypher queries.
func EscapeString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	s = strings.ReplaceAll(s, "\n", "\\n")
	s = strings.ReplaceAll(s, "\r", "\\r")
	return s
}

// EscapeKey ensures a key is valid for Cypher property names.
func EscapeKey(s string) string {
	result := strings.Builder{}
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			result.WriteRune(r)
		} else {
			result.WriteRune('_')
		}
	}
	return result.String()
}

// ToNeoLabel converts a graphize node type to a Neo4j label.
// Example: "function" -> "Function", "method_call" -> "MethodCall"
func ToNeoLabel(nodeType string) string {
	parts := strings.Split(nodeType, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	label := strings.Join(parts, "")

	// Ensure it starts with a letter
	if len(label) > 0 && label[0] >= '0' && label[0] <= '9' {
		label = "N" + label
	}

	if label == "" {
		return "Node"
	}

	return label
}

// ToNeoRelType converts a graphize edge type to a Neo4j relationship type.
// Neo4j relationship types are typically UPPERCASE.
func ToNeoRelType(edgeType string) string {
	return strings.ToUpper(edgeType)
}
