package output

import (
	"fmt"
	"sort"
	"strings"

	"github.com/plexusone/graphfs/pkg/graph"
)

// SummaryOptions configures summary markdown generation.
type SummaryOptions struct {
	// TopN is the number of top nodes to show per category.
	TopN int
}

// GenerateSummaryMarkdown generates a markdown summary of the graph.
func GenerateSummaryMarkdown(nodes []*graph.Node, edges []*graph.Edge, opts SummaryOptions) string {
	topN := opts.TopN
	if topN <= 0 {
		topN = 10
	}

	// Build adjacency for degree calculation
	inDegree := make(map[string]int)
	outDegree := make(map[string]int)
	for _, e := range edges {
		outDegree[e.From]++
		inDegree[e.To]++
	}

	// Count by type
	nodesByType := make(map[string]int)
	edgesByType := make(map[string]int)
	packageNodes := make(map[string][]string) // package -> functions/types

	for _, n := range nodes {
		nodesByType[n.Type]++
		if n.Type == "function" || n.Type == "method" || n.Type == "struct" || n.Type == "interface" {
			// Extract package from ID (format: pkg.Name or pkg.Type.Method)
			parts := strings.Split(n.ID, ".")
			if len(parts) >= 2 {
				pkg := parts[0]
				packageNodes[pkg] = append(packageNodes[pkg], n.Label)
			}
		}
	}

	for _, e := range edges {
		edgesByType[e.Type]++
	}

	// Find hub nodes (highest total degree)
	type nodeScore struct {
		id       string
		label    string
		nodeType string
		inDeg    int
		outDeg   int
		total    int
	}

	var scores []nodeScore
	for _, n := range nodes {
		in := inDegree[n.ID]
		out := outDegree[n.ID]
		scores = append(scores, nodeScore{
			id:       n.ID,
			label:    n.Label,
			nodeType: n.Type,
			inDeg:    in,
			outDeg:   out,
			total:    in + out,
		})
	}

	sort.Slice(scores, func(i, j int) bool {
		return scores[i].total > scores[j].total
	})

	// Generate markdown
	var sb strings.Builder

	sb.WriteString("# Graph Summary\n\n")
	sb.WriteString("*Auto-generated by graphize. For AI agent context.*\n\n")

	// Statistics
	sb.WriteString("## Statistics\n\n")
	fmt.Fprintf(&sb, "- **Total Nodes:** %d\n", len(nodes))
	fmt.Fprintf(&sb, "- **Total Edges:** %d\n", len(edges))
	sb.WriteString("\n")

	// Node types
	sb.WriteString("### Node Types\n\n")
	sb.WriteString("| Type | Count |\n|------|-------|\n")
	sortedNodeTypes := sortedKeys(nodesByType)
	for _, t := range sortedNodeTypes {
		fmt.Fprintf(&sb, "| %s | %d |\n", t, nodesByType[t])
	}
	sb.WriteString("\n")

	// Edge types
	sb.WriteString("### Edge Types\n\n")
	sb.WriteString("| Type | Count |\n|------|-------|\n")
	sortedEdgeTypes := sortedKeys(edgesByType)
	for _, t := range sortedEdgeTypes {
		fmt.Fprintf(&sb, "| %s | %d |\n", t, edgesByType[t])
	}
	sb.WriteString("\n")

	// Hub nodes
	sb.WriteString("## Key Nodes (Hubs)\n\n")
	sb.WriteString("Nodes with the most connections, likely central to the codebase.\n\n")
	sb.WriteString("| Node | Type | In | Out | Total |\n|------|------|----|----|-------|\n")
	limit := topN
	if limit > len(scores) {
		limit = len(scores)
	}
	for i := 0; i < limit; i++ {
		s := scores[i]
		label := s.label
		if len(label) > 40 {
			label = label[:37] + "..."
		}
		fmt.Fprintf(&sb, "| %s | %s | %d | %d | %d |\n",
			label, s.nodeType, s.inDeg, s.outDeg, s.total)
	}
	sb.WriteString("\n")

	// Package overview
	sb.WriteString("## Package Overview\n\n")
	fmt.Fprintf(&sb, "Found %d packages.\n\n", len(packageNodes))

	// Sort packages by size
	type pkgSize struct {
		name  string
		count int
	}
	var pkgs []pkgSize
	for name, items := range packageNodes {
		pkgs = append(pkgs, pkgSize{name, len(items)})
	}
	sort.Slice(pkgs, func(i, j int) bool {
		return pkgs[i].count > pkgs[j].count
	})

	sb.WriteString("| Package | Items |\n|---------|-------|\n")
	pkgLimit := 20
	if pkgLimit > len(pkgs) {
		pkgLimit = len(pkgs)
	}
	for i := 0; i < pkgLimit; i++ {
		fmt.Fprintf(&sb, "| %s | %d |\n", pkgs[i].name, pkgs[i].count)
	}
	if len(pkgs) > 20 {
		fmt.Fprintf(&sb, "| ... | *(%d more)* |\n", len(pkgs)-20)
	}
	sb.WriteString("\n")

	// Usage note
	sb.WriteString("## Usage\n\n")
	sb.WriteString("To explore the full graph interactively:\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("graphize export html -o graph.html && open graph.html\n")
	sb.WriteString("```\n\n")
	sb.WriteString("To query specific nodes:\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("graphize query <node-id> --depth 2\n")
	sb.WriteString("```\n")

	return sb.String()
}

// sortedKeys returns the keys of a map[string]int sorted alphabetically.
func sortedKeys(m map[string]int) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
