package output

import (
	"compress/gzip"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/plexusone/graphfs/pkg/graph"
	toon "github.com/toon-format/toon-go"
)

// TOONOptions configures TOON output generation.
type TOONOptions struct {
	// NoExtra excludes source locations and extra metadata.
	NoExtra bool

	// Compact uses shorter IDs and implies NoExtra.
	Compact bool
}

// GraphExport represents the TOON export structure for a graph.
type GraphExport struct {
	Stats Stats             `toon:"stats"`
	Nodes map[string][]Node `toon:"nodes"`
	Edges map[string][]Edge `toon:"edges"`
}

// Stats contains graph statistics.
type Stats struct {
	Nodes int `toon:"nodes"`
	Edges int `toon:"edges"`
}

// Node represents a node in TOON export.
type Node struct {
	ID      string `toon:"id"`
	Label   string `toon:"label,omitempty"`
	Package string `toon:"pkg,omitempty"`
	File    string `toon:"file,omitempty"`
}

// Edge represents an edge in TOON export.
type Edge struct {
	From            string  `toon:"from"`
	To              string  `toon:"to"`
	Confidence      string  `toon:"confidence,omitempty"`
	ConfidenceScore float64 `toon:"confidence_score,omitempty"`
}

// GenerateTOON generates TOON format output from nodes and edges.
func GenerateTOON(nodes []*graph.Node, edges []*graph.Edge, opts TOONOptions) string {
	// Compact implies NoExtra
	noExtra := opts.NoExtra || opts.Compact

	// Group nodes by type
	nodesByType := make(map[string][]*graph.Node)
	for _, n := range nodes {
		nodesByType[n.Type] = append(nodesByType[n.Type], n)
	}

	// Sort types for deterministic output
	nodeTypes := make([]string, 0, len(nodesByType))
	for t := range nodesByType {
		nodeTypes = append(nodeTypes, t)
	}
	sort.Strings(nodeTypes)

	// Build nodes map
	exportNodes := make(map[string][]Node)
	for _, nodeType := range nodeTypes {
		typeNodes := nodesByType[nodeType]

		// Sort nodes by ID for deterministic output
		sort.Slice(typeNodes, func(i, j int) bool {
			return typeNodes[i].ID < typeNodes[j].ID
		})

		var nodeList []Node
		for _, n := range typeNodes {
			id := n.ID
			if opts.Compact {
				id = CompactID(id)
			}

			node := Node{ID: id}

			if n.Label != "" && n.Label != n.ID {
				node.Label = n.Label
			}

			// Extra metadata (optional)
			if !noExtra && n.Attrs != nil {
				if pkg := n.Attrs["package"]; pkg != "" {
					node.Package = pkg
				}
				if file := n.Attrs["source_file"]; file != "" {
					node.File = file
				}
			}

			nodeList = append(nodeList, node)
		}
		exportNodes[nodeType] = nodeList
	}

	// Group edges by type
	edgesByType := make(map[string][]*graph.Edge)
	for _, e := range edges {
		edgesByType[e.Type] = append(edgesByType[e.Type], e)
	}

	// Sort edge types
	edgeTypes := make([]string, 0, len(edgesByType))
	for t := range edgesByType {
		edgeTypes = append(edgeTypes, t)
	}
	sort.Strings(edgeTypes)

	// Build edges map
	exportEdges := make(map[string][]Edge)
	for _, edgeType := range edgeTypes {
		typeEdges := edgesByType[edgeType]

		// Sort edges for deterministic output
		sort.Slice(typeEdges, func(i, j int) bool {
			if typeEdges[i].From != typeEdges[j].From {
				return typeEdges[i].From < typeEdges[j].From
			}
			return typeEdges[i].To < typeEdges[j].To
		})

		var edgeList []Edge
		for _, e := range typeEdges {
			from := e.From
			to := e.To
			if opts.Compact {
				from = CompactID(from)
				to = CompactID(to)
			}

			edge := Edge{From: from, To: to}

			// Include confidence for non-EXTRACTED edges (LLM-inferred)
			if !noExtra && e.Confidence != "" && e.Confidence != graph.ConfidenceExtracted {
				edge.Confidence = string(e.Confidence)
				if e.ConfidenceScore > 0 {
					edge.ConfidenceScore = e.ConfidenceScore
				}
			}

			edgeList = append(edgeList, edge)
		}
		exportEdges[edgeType] = edgeList
	}

	// Build export struct
	export := GraphExport{
		Stats: Stats{
			Nodes: len(nodes),
			Edges: len(edges),
		},
		Nodes: exportNodes,
		Edges: exportEdges,
	}

	// Marshal to TOON
	result, err := toon.MarshalString(export)
	if err != nil {
		// Fallback to basic format on error
		return fmt.Sprintf("# Graph Export Error: %v\n", err)
	}

	// Add header comment
	header := "# Graph Export (TOON format)\n# Generated by graphize\n\n"
	return header + result
}

// WriteTOONGzipped writes TOON content to a gzip-compressed file.
func WriteTOONGzipped(path string, content string) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("creating output file: %w", err)
	}
	defer func() { _ = f.Close() }()

	gw := gzip.NewWriter(f)
	defer func() { _ = gw.Close() }()

	if _, err := gw.Write([]byte(content)); err != nil {
		return fmt.Errorf("writing gzipped content: %w", err)
	}

	return nil
}

// CompactID shortens verbose IDs for compact mode.
func CompactID(id string) string {
	prefixes := []string{"constant_", "func_", "method_", "struct_", "interface_", "type_", "var_", "pkg_", "file_"}
	for _, p := range prefixes {
		if strings.HasPrefix(id, p) {
			return strings.TrimPrefix(id, p)
		}
	}
	return id
}

// FormatSize formats a byte size as a human-readable string.
func FormatSize(bytes int64) string {
	const unit = 1024
	if bytes < unit {
		return fmt.Sprintf("%d B", bytes)
	}
	div, exp := int64(unit), 0
	for n := bytes / unit; n >= unit; n /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %cB", float64(bytes)/float64(div), "KMGTPE"[exp])
}
