package output

import (
	"compress/gzip"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/plexusone/graphfs/pkg/graph"
)

// TOONOptions configures TOON output generation.
type TOONOptions struct {
	// NoExtra excludes source locations and extra metadata.
	NoExtra bool

	// Compact uses shorter IDs and implies NoExtra.
	Compact bool
}

// GenerateTOON generates TOON format output from nodes and edges.
func GenerateTOON(nodes []*graph.Node, edges []*graph.Edge, opts TOONOptions) string {
	var sb strings.Builder

	// Compact implies NoExtra
	noExtra := opts.NoExtra || opts.Compact

	// Header
	sb.WriteString("# Graph Export (TOON format)\n")
	sb.WriteString("# Generated by graphize\n\n")

	// Stats
	sb.WriteString("stats\n")
	fmt.Fprintf(&sb, "  nodes: %d\n", len(nodes))
	fmt.Fprintf(&sb, "  edges: %d\n", len(edges))
	sb.WriteString("\n")

	// Group nodes by type
	nodesByType := make(map[string][]*graph.Node)
	for _, n := range nodes {
		nodesByType[n.Type] = append(nodesByType[n.Type], n)
	}

	// Sort types for deterministic output
	nodeTypes := make([]string, 0, len(nodesByType))
	for t := range nodesByType {
		nodeTypes = append(nodeTypes, t)
	}
	sort.Strings(nodeTypes)

	// Write nodes
	sb.WriteString("nodes\n")
	for _, nodeType := range nodeTypes {
		typeNodes := nodesByType[nodeType]
		fmt.Fprintf(&sb, "  %s: %d\n", nodeType, len(typeNodes))

		// Sort nodes by ID for deterministic output
		sort.Slice(typeNodes, func(i, j int) bool {
			return typeNodes[i].ID < typeNodes[j].ID
		})

		for _, n := range typeNodes {
			id := n.ID
			if opts.Compact {
				id = CompactID(id)
			}

			if n.Label != "" && n.Label != n.ID {
				fmt.Fprintf(&sb, "    - %s | %s\n", id, n.Label)
			} else {
				fmt.Fprintf(&sb, "    - %s\n", id)
			}

			// Extra metadata (optional)
			if !noExtra && n.Attrs != nil {
				if pkg := n.Attrs["package"]; pkg != "" {
					fmt.Fprintf(&sb, "      pkg: %s\n", pkg)
				}
				if file := n.Attrs["source_file"]; file != "" {
					fmt.Fprintf(&sb, "      file: %s\n", file)
				}
			}
		}
	}
	sb.WriteString("\n")

	// Group edges by type
	edgesByType := make(map[string][]*graph.Edge)
	for _, e := range edges {
		edgesByType[e.Type] = append(edgesByType[e.Type], e)
	}

	// Sort types
	edgeTypes := make([]string, 0, len(edgesByType))
	for t := range edgesByType {
		edgeTypes = append(edgeTypes, t)
	}
	sort.Strings(edgeTypes)

	// Write edges
	sb.WriteString("edges\n")
	for _, edgeType := range edgeTypes {
		typeEdges := edgesByType[edgeType]
		fmt.Fprintf(&sb, "  %s: %d\n", edgeType, len(typeEdges))

		// Sort edges for deterministic output
		sort.Slice(typeEdges, func(i, j int) bool {
			if typeEdges[i].From != typeEdges[j].From {
				return typeEdges[i].From < typeEdges[j].From
			}
			return typeEdges[i].To < typeEdges[j].To
		})

		for _, e := range typeEdges {
			from := e.From
			to := e.To
			if opts.Compact {
				from = CompactID(from)
				to = CompactID(to)
			}
			// Include confidence for non-EXTRACTED edges (LLM-inferred)
			if !noExtra && e.Confidence != "" && e.Confidence != graph.ConfidenceExtracted {
				fmt.Fprintf(&sb, "    - %s -> %s [%s %.2f]\n", from, to, e.Confidence, e.ConfidenceScore)
			} else {
				fmt.Fprintf(&sb, "    - %s -> %s\n", from, to)
			}
		}
	}

	return sb.String()
}

// WriteTOONGzipped writes TOON content to a gzip-compressed file.
func WriteTOONGzipped(path string, content string) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("creating output file: %w", err)
	}
	defer func() { _ = f.Close() }()

	gw := gzip.NewWriter(f)
	defer func() { _ = gw.Close() }()

	if _, err := gw.Write([]byte(content)); err != nil {
		return fmt.Errorf("writing gzipped content: %w", err)
	}

	return nil
}

// CompactID shortens verbose IDs for compact mode.
func CompactID(id string) string {
	prefixes := []string{"constant_", "func_", "method_", "struct_", "interface_", "type_", "var_", "pkg_", "file_"}
	for _, p := range prefixes {
		if strings.HasPrefix(id, p) {
			return strings.TrimPrefix(id, p)
		}
	}
	return id
}

// FormatSize formats a byte size as a human-readable string.
func FormatSize(bytes int64) string {
	const unit = 1024
	if bytes < unit {
		return fmt.Sprintf("%d B", bytes)
	}
	div, exp := int64(unit), 0
	for n := bytes / unit; n >= unit; n /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %cB", float64(bytes)/float64(div), "KMGTPE"[exp])
}
