package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/plexusone/graphfs/pkg/graph"
	"github.com/plexusone/graphfs/pkg/store"
	"github.com/plexusone/graphize/pkg/metrics"
	"github.com/spf13/cobra"
)

var exportCypherCmd = &cobra.Command{
	Use:   "cypher",
	Short: "Export graph as Neo4j Cypher statements",
	Long: `Export the graph as Neo4j Cypher CREATE statements.

The output can be used to import the graph into Neo4j:
  - Copy/paste into Neo4j Browser
  - Use cypher-shell: cat graph.cypher | cypher-shell -u neo4j -p password
  - Use neo4j-admin import

Examples:
  graphize export cypher -o graph.cypher
  graphize export cypher | cypher-shell -u neo4j -p secret`,
	RunE: runExportCypher,
}

var cypherOutput string

func init() {
	exportCmd.AddCommand(exportCypherCmd)
	exportCypherCmd.Flags().StringVarP(&cypherOutput, "output", "o", "", "Output file path (stdout if not specified)")
}

func runExportCypher(cmd *cobra.Command, args []string) error {
	path := graphPath
	if path == "" {
		path = ".graphize"
	}

	s, err := store.NewFSStore(path)
	if err != nil {
		return fmt.Errorf("opening graph store: %w", err)
	}

	nodes, err := s.ListNodes()
	if err != nil {
		return fmt.Errorf("listing nodes: %w", err)
	}

	edges, err := s.ListEdges()
	if err != nil {
		return fmt.Errorf("listing edges: %w", err)
	}

	if len(nodes) == 0 {
		return fmt.Errorf("no nodes found. Run 'graphize analyze' first")
	}

	// Generate Cypher
	cypher := generateCypher(nodes, edges)

	// Output
	if cypherOutput == "" {
		// Write to stdout
		fmt.Print(cypher)
		return nil
	}

	// Write to file
	if dir := filepath.Dir(cypherOutput); dir != "." {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("creating output directory: %w", err)
		}
	}

	if err := os.WriteFile(cypherOutput, []byte(cypher), 0600); err != nil {
		return fmt.Errorf("writing output file: %w", err)
	}

	// Report stats
	fi, _ := os.Stat(cypherOutput)
	fmt.Fprintf(os.Stderr, "Exported graph to %s\n", cypherOutput)
	fmt.Fprintf(os.Stderr, "  Nodes: %d\n", len(nodes))
	fmt.Fprintf(os.Stderr, "  Edges: %d\n", len(edges))
	if fi != nil {
		fmt.Fprintf(os.Stderr, "  Size: %s\n", metrics.FormatBytes(fi.Size()))
	}

	return nil
}

// generateCypher generates Neo4j Cypher CREATE statements for the graph.
func generateCypher(nodes []*graph.Node, edges []*graph.Edge) string {
	var sb strings.Builder

	sb.WriteString("// Neo4j Cypher import script\n")
	sb.WriteString("// Generated by graphize\n")
	sb.WriteString("//\n")
	sb.WriteString("// Usage:\n")
	sb.WriteString("//   cat graph.cypher | cypher-shell -u neo4j -p password\n")
	sb.WriteString("//   Or paste into Neo4j Browser\n")
	sb.WriteString("\n")

	// Create constraints for unique IDs
	sb.WriteString("// Create constraint for unique node IDs\n")
	sb.WriteString("CREATE CONSTRAINT node_id IF NOT EXISTS FOR (n:Node) REQUIRE n.id IS UNIQUE;\n\n")

	// Create nodes
	sb.WriteString("// Create nodes\n")
	for _, n := range nodes {
		cypher := nodeToCreate(n)
		sb.WriteString(cypher)
		sb.WriteString("\n")
	}
	sb.WriteString("\n")

	// Create edges
	sb.WriteString("// Create relationships\n")
	for _, e := range edges {
		cypher := edgeToCreate(e)
		sb.WriteString(cypher)
		sb.WriteString("\n")
	}

	return sb.String()
}

// nodeToCreate generates a CREATE statement for a node.
func nodeToCreate(n *graph.Node) string {
	// Escape strings for Cypher
	id := escapeCypher(n.ID)
	label := escapeCypher(n.Label)
	nodeType := escapeCypher(n.Type)

	// Build properties
	props := []string{
		fmt.Sprintf("id: '%s'", id),
		fmt.Sprintf("type: '%s'", nodeType),
	}

	if label != "" && label != id {
		props = append(props, fmt.Sprintf("label: '%s'", label))
	}

	// Add attributes
	for k, v := range n.Attrs {
		if v != "" {
			props = append(props, fmt.Sprintf("%s: '%s'", escapeCypherKey(k), escapeCypher(v)))
		}
	}

	// Use node type as Neo4j label
	neoLabel := toNeoLabel(n.Type)

	return fmt.Sprintf("CREATE (:%s {%s});", neoLabel, strings.Join(props, ", "))
}

// edgeToCreate generates a CREATE statement for an edge.
func edgeToCreate(e *graph.Edge) string {
	from := escapeCypher(e.From)
	to := escapeCypher(e.To)
	relType := toNeoRelType(e.Type)

	// Build properties
	var props []string

	if e.Confidence != "" {
		props = append(props, fmt.Sprintf("confidence: '%s'", escapeCypher(string(e.Confidence))))
	}

	if e.ConfidenceScore > 0 {
		props = append(props, fmt.Sprintf("confidence_score: %f", e.ConfidenceScore))
	}

	// Add attributes
	for k, v := range e.Attrs {
		if v != "" {
			props = append(props, fmt.Sprintf("%s: '%s'", escapeCypherKey(k), escapeCypher(v)))
		}
	}

	var propsStr string
	if len(props) > 0 {
		propsStr = fmt.Sprintf(" {%s}", strings.Join(props, ", "))
	}

	return fmt.Sprintf("MATCH (a:Node {id: '%s'}), (b:Node {id: '%s'}) CREATE (a)-[:%s%s]->(b);",
		from, to, relType, propsStr)
}

// escapeCypher escapes a string for use in Cypher queries.
func escapeCypher(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	s = strings.ReplaceAll(s, "\n", "\\n")
	s = strings.ReplaceAll(s, "\r", "\\r")
	return s
}

// escapeCypherKey ensures a key is valid for Cypher property names.
func escapeCypherKey(s string) string {
	// Replace invalid characters with underscores
	result := strings.Builder{}
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			result.WriteRune(r)
		} else {
			result.WriteRune('_')
		}
	}
	return result.String()
}

// toNeoLabel converts a graphize node type to a Neo4j label.
func toNeoLabel(nodeType string) string {
	// Capitalize first letter and remove underscores
	parts := strings.Split(nodeType, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	label := strings.Join(parts, "")

	// Ensure it starts with a letter
	if len(label) > 0 && label[0] >= '0' && label[0] <= '9' {
		label = "N" + label
	}

	if label == "" {
		return "Node"
	}

	return label
}

// toNeoRelType converts a graphize edge type to a Neo4j relationship type.
func toNeoRelType(edgeType string) string {
	// Neo4j relationship types are typically uppercase with underscores
	return strings.ToUpper(edgeType)
}
