package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/plexusone/graphfs/pkg/analyze"
	"github.com/plexusone/graphfs/pkg/graph"
	"github.com/plexusone/graphfs/pkg/store"
	"github.com/spf13/cobra"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

var exportObsidianCmd = &cobra.Command{
	Use:   "obsidian",
	Short: "Export graph as Obsidian vault",
	Long: `Export the graph as an Obsidian vault with wikilinks.

Creates a wiki-style structure with:
  - index.md: Entry point with god nodes and overview
  - communities/: One page per detected community
  - nodes/: One page per significant node (functions, types)

Pages are interconnected with [[wikilinks]] for easy navigation.

Examples:
  graphize export obsidian -o ./vault
  graphize export obsidian -o ~/obsidian/code-graph`,
	RunE: runExportObsidian,
}

var (
	obsidianOutput string
	obsidianTopN   int
	obsidianMinDeg int
)

func init() {
	exportCmd.AddCommand(exportObsidianCmd)
	exportObsidianCmd.Flags().StringVarP(&obsidianOutput, "output", "o", "", "Output directory (required)")
	exportObsidianCmd.Flags().IntVar(&obsidianTopN, "top", 20, "Number of top nodes to include as individual pages")
	exportObsidianCmd.Flags().IntVar(&obsidianMinDeg, "min-degree", 3, "Minimum degree for a node to get its own page")
	_ = exportObsidianCmd.MarkFlagRequired("output")
}

func runExportObsidian(cmd *cobra.Command, args []string) error {
	path := graphPath
	if path == "" {
		path = ".graphize"
	}

	s, err := store.NewFSStore(path)
	if err != nil {
		return fmt.Errorf("opening graph store: %w", err)
	}

	nodes, err := s.ListNodes()
	if err != nil {
		return fmt.Errorf("listing nodes: %w", err)
	}

	edges, err := s.ListEdges()
	if err != nil {
		return fmt.Errorf("listing edges: %w", err)
	}

	if len(nodes) == 0 {
		return fmt.Errorf("no nodes found. Run 'graphize analyze' first")
	}

	// Create output directories
	if err := os.MkdirAll(obsidianOutput, 0755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(obsidianOutput, "communities"), 0755); err != nil {
		return fmt.Errorf("creating communities directory: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(obsidianOutput, "nodes"), 0755); err != nil {
		return fmt.Errorf("creating nodes directory: %w", err)
	}

	// Calculate node degrees
	degrees := make(map[string]int)
	for _, e := range edges {
		degrees[e.From]++
		degrees[e.To]++
	}

	// Find god nodes
	godNodes := analyze.FindHubs(nodes, edges, obsidianTopN, nil)

	// Detect communities
	communities := analyze.DetectCommunities(nodes, edges)

	// Build node map
	nodeMap := make(map[string]*graph.Node)
	for _, n := range nodes {
		nodeMap[n.ID] = n
	}

	// Build adjacency for neighbor lookup
	outgoing := make(map[string][]*graph.Edge)
	incoming := make(map[string][]*graph.Edge)
	for _, e := range edges {
		outgoing[e.From] = append(outgoing[e.From], e)
		incoming[e.To] = append(incoming[e.To], e)
	}

	// Generate index.md
	if err := generateObsidianIndex(obsidianOutput, nodes, edges, godNodes, communities); err != nil {
		return fmt.Errorf("generating index: %w", err)
	}

	// Generate community pages
	for _, comm := range communities.Communities {
		if err := generateObsidianCommunity(obsidianOutput, comm, nodeMap, degrees); err != nil {
			return fmt.Errorf("generating community %d: %w", comm.ID, err)
		}
	}

	// Generate node pages for significant nodes
	nodePages := 0
	for _, hub := range godNodes {
		if degrees[hub.ID] >= obsidianMinDeg {
			node := nodeMap[hub.ID]
			if node != nil {
				if err := generateObsidianNode(obsidianOutput, node, outgoing, incoming, nodeMap); err != nil {
					return fmt.Errorf("generating node %s: %w", node.ID, err)
				}
				nodePages++
			}
		}
	}

	// Report
	fmt.Printf("Exported Obsidian vault to %s\n", obsidianOutput)
	fmt.Printf("  index.md: Overview with %d god nodes\n", len(godNodes))
	fmt.Printf("  communities/: %d community pages\n", len(communities.Communities))
	fmt.Printf("  nodes/: %d node pages\n", nodePages)

	return nil
}

func generateObsidianIndex(outputDir string, nodes []*graph.Node, edges []*graph.Edge, godNodes []analyze.HubNode, communities *analyze.ClusterResult) error {
	var sb strings.Builder

	sb.WriteString("# Code Knowledge Graph\n\n")
	sb.WriteString("*Generated by graphize*\n\n")

	// Stats
	sb.WriteString("## Overview\n\n")
	fmt.Fprintf(&sb, "- **Nodes:** %d\n", len(nodes))
	fmt.Fprintf(&sb, "- **Edges:** %d\n", len(edges))
	fmt.Fprintf(&sb, "- **Communities:** %d\n", len(communities.Communities))
	if communities.Modularity > 0 {
		fmt.Fprintf(&sb, "- **Modularity:** %.4f\n", communities.Modularity)
	}
	sb.WriteString("\n")

	// God nodes
	sb.WriteString("## Key Nodes\n\n")
	sb.WriteString("Most connected entities in the codebase:\n\n")
	sb.WriteString("| Node | Type | Connections |\n")
	sb.WriteString("|------|------|-------------|\n")
	for _, hub := range godNodes {
		name := sanitizeObsidianName(hub.ID)
		fmt.Fprintf(&sb, "| [[nodes/%s|%s]] | %s | %d |\n",
			name, hub.Label, hub.Type, hub.InDegree+hub.OutDegree)
	}
	sb.WriteString("\n")

	// Communities
	sb.WriteString("## Communities\n\n")
	sb.WriteString("Clusters of related code:\n\n")
	for _, comm := range communities.Communities {
		name := fmt.Sprintf("community-%d", comm.ID)
		fmt.Fprintf(&sb, "- [[communities/%s|Community %d]] (%d members, cohesion: %.2f)\n",
			name, comm.ID, comm.Size, comm.Cohesion)
	}
	sb.WriteString("\n")

	// Navigation
	sb.WriteString("## Navigation\n\n")
	sb.WriteString("- Browse [[communities/]] for code clusters\n")
	sb.WriteString("- Browse [[nodes/]] for individual entities\n")

	return os.WriteFile(filepath.Join(outputDir, "index.md"), []byte(sb.String()), 0600)
}

func generateObsidianCommunity(outputDir string, comm analyze.Community, nodeMap map[string]*graph.Node, degrees map[string]int) error {
	var sb strings.Builder

	fmt.Fprintf(&sb, "# Community %d\n\n", comm.ID)
	fmt.Fprintf(&sb, "**Size:** %d members\n", comm.Size)
	fmt.Fprintf(&sb, "**Cohesion:** %.2f\n\n", comm.Cohesion)

	// Group members by type
	membersByType := make(map[string][]string)
	for _, memberID := range comm.Members {
		node := nodeMap[memberID]
		if node != nil {
			membersByType[node.Type] = append(membersByType[node.Type], memberID)
		}
	}

	// Sort types
	var types []string
	for t := range membersByType {
		types = append(types, t)
	}
	sort.Strings(types)

	sb.WriteString("## Members\n\n")
	for _, nodeType := range types {
		members := membersByType[nodeType]
		fmt.Fprintf(&sb, "### %s (%d)\n\n", cases.Title(language.English).String(nodeType), len(members))

		// Sort by degree
		sort.Slice(members, func(i, j int) bool {
			return degrees[members[i]] > degrees[members[j]]
		})

		for _, memberID := range members {
			node := nodeMap[memberID]
			label := node.Label
			if label == "" {
				label = node.ID
			}
			name := sanitizeObsidianName(node.ID)
			if degrees[memberID] >= 3 {
				fmt.Fprintf(&sb, "- [[nodes/%s|%s]] (%d connections)\n", name, label, degrees[memberID])
			} else {
				fmt.Fprintf(&sb, "- %s (%d connections)\n", label, degrees[memberID])
			}
		}
		sb.WriteString("\n")
	}

	// Navigation
	sb.WriteString("---\n\n")
	sb.WriteString("[[../index|← Back to Index]]\n")

	filename := fmt.Sprintf("community-%d.md", comm.ID)
	return os.WriteFile(filepath.Join(outputDir, "communities", filename), []byte(sb.String()), 0600)
}

func generateObsidianNode(outputDir string, node *graph.Node, outgoing, incoming map[string][]*graph.Edge, nodeMap map[string]*graph.Node) error {
	var sb strings.Builder

	label := node.Label
	if label == "" {
		label = node.ID
	}

	fmt.Fprintf(&sb, "# %s\n\n", label)
	fmt.Fprintf(&sb, "**Type:** %s\n", node.Type)
	fmt.Fprintf(&sb, "**ID:** `%s`\n", node.ID)

	// Attributes
	if len(node.Attrs) > 0 {
		sb.WriteString("\n## Attributes\n\n")
		for k, v := range node.Attrs {
			if v != "" {
				fmt.Fprintf(&sb, "- **%s:** %s\n", k, v)
			}
		}
	}

	// Outgoing edges (what this node references)
	outEdges := outgoing[node.ID]
	if len(outEdges) > 0 {
		sb.WriteString("\n## References\n\n")
		sb.WriteString("What this node references:\n\n")

		// Group by edge type
		byType := make(map[string][]*graph.Edge)
		for _, e := range outEdges {
			byType[e.Type] = append(byType[e.Type], e)
		}

		for edgeType, typeEdges := range byType {
			fmt.Fprintf(&sb, "### %s\n\n", edgeType)
			for _, e := range typeEdges {
				target := nodeMap[e.To]
				if target != nil {
					targetLabel := target.Label
					if targetLabel == "" {
						targetLabel = target.ID
					}
					name := sanitizeObsidianName(target.ID)
					fmt.Fprintf(&sb, "- [[nodes/%s|%s]]\n", name, targetLabel)
				}
			}
			sb.WriteString("\n")
		}
	}

	// Incoming edges (what references this node)
	inEdges := incoming[node.ID]
	if len(inEdges) > 0 {
		sb.WriteString("\n## Referenced By\n\n")
		sb.WriteString("What references this node:\n\n")

		// Group by edge type
		byType := make(map[string][]*graph.Edge)
		for _, e := range inEdges {
			byType[e.Type] = append(byType[e.Type], e)
		}

		for edgeType, typeEdges := range byType {
			fmt.Fprintf(&sb, "### %s\n\n", edgeType)
			for _, e := range typeEdges {
				source := nodeMap[e.From]
				if source != nil {
					sourceLabel := source.Label
					if sourceLabel == "" {
						sourceLabel = source.ID
					}
					name := sanitizeObsidianName(source.ID)
					fmt.Fprintf(&sb, "- [[nodes/%s|%s]]\n", name, sourceLabel)
				}
			}
			sb.WriteString("\n")
		}
	}

	// Navigation
	sb.WriteString("---\n\n")
	sb.WriteString("[[../index|← Back to Index]]\n")

	filename := sanitizeObsidianName(node.ID) + ".md"
	return os.WriteFile(filepath.Join(outputDir, "nodes", filename), []byte(sb.String()), 0600)
}

// sanitizeObsidianName creates a safe filename for Obsidian
func sanitizeObsidianName(id string) string {
	// Replace characters that are problematic in filenames or wikilinks
	name := strings.ReplaceAll(id, "/", "_")
	name = strings.ReplaceAll(name, "\\", "_")
	name = strings.ReplaceAll(name, ":", "_")
	name = strings.ReplaceAll(name, "*", "_")
	name = strings.ReplaceAll(name, "?", "_")
	name = strings.ReplaceAll(name, "\"", "_")
	name = strings.ReplaceAll(name, "<", "_")
	name = strings.ReplaceAll(name, ">", "_")
	name = strings.ReplaceAll(name, "|", "_")
	return name
}
