// Package obsidian generates Obsidian vault exports from graph data.
package obsidian

import (
	"fmt"
	"sort"
	"strings"

	"github.com/plexusone/graphfs/pkg/analyze"
	"github.com/plexusone/graphfs/pkg/graph"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

// Generator creates Obsidian markdown pages from graph data.
type Generator struct {
	// TopN is the number of top hub nodes to include.
	TopN int

	// MinDegree is the minimum degree for a node to get its own page.
	MinDegree int
}

// NewGenerator creates a Generator with default settings.
func NewGenerator() *Generator {
	return &Generator{
		TopN:      20,
		MinDegree: 3,
	}
}

// VaultContent holds all generated content for an Obsidian vault.
type VaultContent struct {
	Index       string
	Communities map[int]string    // community ID -> content
	Nodes       map[string]string // sanitized node ID -> content
}

// Generate creates all content for an Obsidian vault.
func (g *Generator) Generate(nodes []*graph.Node, edges []*graph.Edge) *VaultContent {
	// Calculate node degrees
	degrees := make(map[string]int)
	for _, e := range edges {
		degrees[e.From]++
		degrees[e.To]++
	}

	// Find hub nodes
	godNodes := analyze.FindHubs(nodes, edges, g.TopN, nil)

	// Detect communities
	communities := analyze.DetectCommunities(nodes, edges)

	// Build node map
	nodeMap := make(map[string]*graph.Node)
	for _, n := range nodes {
		nodeMap[n.ID] = n
	}

	// Build adjacency for neighbor lookup
	outgoing := make(map[string][]*graph.Edge)
	incoming := make(map[string][]*graph.Edge)
	for _, e := range edges {
		outgoing[e.From] = append(outgoing[e.From], e)
		incoming[e.To] = append(incoming[e.To], e)
	}

	result := &VaultContent{
		Communities: make(map[int]string),
		Nodes:       make(map[string]string),
	}

	// Generate index
	result.Index = GenerateIndex(nodes, edges, godNodes, communities)

	// Generate community pages
	for _, comm := range communities.Communities {
		result.Communities[comm.ID] = GenerateCommunity(comm, nodeMap, degrees)
	}

	// Generate node pages for significant nodes
	for _, hub := range godNodes {
		if degrees[hub.ID] >= g.MinDegree {
			node := nodeMap[hub.ID]
			if node != nil {
				name := SanitizeName(node.ID)
				result.Nodes[name] = GenerateNode(node, outgoing, incoming, nodeMap)
			}
		}
	}

	return result
}

// GenerateIndex creates the index.md content.
func GenerateIndex(nodes []*graph.Node, edges []*graph.Edge, godNodes []analyze.HubNode, communities *analyze.ClusterResult) string {
	var sb strings.Builder

	sb.WriteString("# Code Knowledge Graph\n\n")
	sb.WriteString("*Generated by graphize*\n\n")

	// Stats
	sb.WriteString("## Overview\n\n")
	fmt.Fprintf(&sb, "- **Nodes:** %d\n", len(nodes))
	fmt.Fprintf(&sb, "- **Edges:** %d\n", len(edges))
	fmt.Fprintf(&sb, "- **Communities:** %d\n", len(communities.Communities))
	if communities.Modularity > 0 {
		fmt.Fprintf(&sb, "- **Modularity:** %.4f\n", communities.Modularity)
	}
	sb.WriteString("\n")

	// God nodes
	sb.WriteString("## Key Nodes\n\n")
	sb.WriteString("Most connected entities in the codebase:\n\n")
	sb.WriteString("| Node | Type | Connections |\n")
	sb.WriteString("|------|------|-------------|\n")
	for _, hub := range godNodes {
		name := SanitizeName(hub.ID)
		fmt.Fprintf(&sb, "| [[nodes/%s|%s]] | %s | %d |\n",
			name, hub.Label, hub.Type, hub.InDegree+hub.OutDegree)
	}
	sb.WriteString("\n")

	// Communities
	sb.WriteString("## Communities\n\n")
	sb.WriteString("Clusters of related code:\n\n")
	for _, comm := range communities.Communities {
		name := fmt.Sprintf("community-%d", comm.ID)
		fmt.Fprintf(&sb, "- [[communities/%s|Community %d]] (%d members, cohesion: %.2f)\n",
			name, comm.ID, comm.Size, comm.Cohesion)
	}
	sb.WriteString("\n")

	// Navigation
	sb.WriteString("## Navigation\n\n")
	sb.WriteString("- Browse [[communities/]] for code clusters\n")
	sb.WriteString("- Browse [[nodes/]] for individual entities\n")

	return sb.String()
}

// GenerateCommunity creates a community page.
func GenerateCommunity(comm analyze.Community, nodeMap map[string]*graph.Node, degrees map[string]int) string {
	var sb strings.Builder

	fmt.Fprintf(&sb, "# Community %d\n\n", comm.ID)
	fmt.Fprintf(&sb, "**Size:** %d members\n", comm.Size)
	fmt.Fprintf(&sb, "**Cohesion:** %.2f\n\n", comm.Cohesion)

	// Group members by type
	membersByType := make(map[string][]string)
	for _, memberID := range comm.Members {
		node := nodeMap[memberID]
		if node != nil {
			membersByType[node.Type] = append(membersByType[node.Type], memberID)
		}
	}

	// Sort types
	var types []string
	for t := range membersByType {
		types = append(types, t)
	}
	sort.Strings(types)

	sb.WriteString("## Members\n\n")
	for _, nodeType := range types {
		members := membersByType[nodeType]
		fmt.Fprintf(&sb, "### %s (%d)\n\n", cases.Title(language.English).String(nodeType), len(members))

		// Sort by degree
		sort.Slice(members, func(i, j int) bool {
			return degrees[members[i]] > degrees[members[j]]
		})

		for _, memberID := range members {
			node := nodeMap[memberID]
			label := node.Label
			if label == "" {
				label = node.ID
			}
			name := SanitizeName(node.ID)
			if degrees[memberID] >= 3 {
				fmt.Fprintf(&sb, "- [[nodes/%s|%s]] (%d connections)\n", name, label, degrees[memberID])
			} else {
				fmt.Fprintf(&sb, "- %s (%d connections)\n", label, degrees[memberID])
			}
		}
		sb.WriteString("\n")
	}

	// Navigation
	sb.WriteString("---\n\n")
	sb.WriteString("[[../index|← Back to Index]]\n")

	return sb.String()
}

// GenerateNode creates a node page.
func GenerateNode(node *graph.Node, outgoing, incoming map[string][]*graph.Edge, nodeMap map[string]*graph.Node) string {
	var sb strings.Builder

	label := node.Label
	if label == "" {
		label = node.ID
	}

	fmt.Fprintf(&sb, "# %s\n\n", label)
	fmt.Fprintf(&sb, "**Type:** %s\n", node.Type)
	fmt.Fprintf(&sb, "**ID:** `%s`\n", node.ID)

	// Attributes
	if len(node.Attrs) > 0 {
		sb.WriteString("\n## Attributes\n\n")
		for k, v := range node.Attrs {
			if v != "" {
				fmt.Fprintf(&sb, "- **%s:** %s\n", k, v)
			}
		}
	}

	// Outgoing edges (what this node references)
	outEdges := outgoing[node.ID]
	if len(outEdges) > 0 {
		sb.WriteString("\n## References\n\n")
		sb.WriteString("What this node references:\n\n")

		// Group by edge type
		byType := groupEdgesByType(outEdges)

		for edgeType, typeEdges := range byType {
			fmt.Fprintf(&sb, "### %s\n\n", edgeType)
			for _, e := range typeEdges {
				target := nodeMap[e.To]
				if target != nil {
					targetLabel := target.Label
					if targetLabel == "" {
						targetLabel = target.ID
					}
					name := SanitizeName(target.ID)
					fmt.Fprintf(&sb, "- [[nodes/%s|%s]]\n", name, targetLabel)
				}
			}
			sb.WriteString("\n")
		}
	}

	// Incoming edges (what references this node)
	inEdges := incoming[node.ID]
	if len(inEdges) > 0 {
		sb.WriteString("\n## Referenced By\n\n")
		sb.WriteString("What references this node:\n\n")

		// Group by edge type
		byType := groupEdgesByType(inEdges)

		for edgeType, typeEdges := range byType {
			fmt.Fprintf(&sb, "### %s\n\n", edgeType)
			for _, e := range typeEdges {
				source := nodeMap[e.From]
				if source != nil {
					sourceLabel := source.Label
					if sourceLabel == "" {
						sourceLabel = source.ID
					}
					name := SanitizeName(source.ID)
					fmt.Fprintf(&sb, "- [[nodes/%s|%s]]\n", name, sourceLabel)
				}
			}
			sb.WriteString("\n")
		}
	}

	// Navigation
	sb.WriteString("---\n\n")
	sb.WriteString("[[../index|← Back to Index]]\n")

	return sb.String()
}

// SanitizeName creates a safe filename for Obsidian.
func SanitizeName(id string) string {
	// Replace characters that are problematic in filenames or wikilinks
	name := strings.ReplaceAll(id, "/", "_")
	name = strings.ReplaceAll(name, "\\", "_")
	name = strings.ReplaceAll(name, ":", "_")
	name = strings.ReplaceAll(name, "*", "_")
	name = strings.ReplaceAll(name, "?", "_")
	name = strings.ReplaceAll(name, "\"", "_")
	name = strings.ReplaceAll(name, "<", "_")
	name = strings.ReplaceAll(name, ">", "_")
	name = strings.ReplaceAll(name, "|", "_")
	return name
}

// groupEdgesByType groups edges by their type.
func groupEdgesByType(edges []*graph.Edge) map[string][]*graph.Edge {
	result := make(map[string][]*graph.Edge)
	for _, e := range edges {
		result[e.Type] = append(result[e.Type], e)
	}
	return result
}
